### ISSUE TITLE
CMakeLists.txt uses features from version newer than declared required version

### ISSUE THREAD

**Issue by firthmj** [GlitchedPolygons/l8w8jwt#13]
The top of the main project CMakeLists.txt declares "cmake_minimum_required(VERSION 3.1)", which should mean it will run on CMake versions V3.1 and higher.

However, the file also has several instances of "add_compile_definitions", which is not available until CMake V3.12.

Changing these to from "add_compile_definitions(xxxxx)" to add_definitions("-Dxxxxx")" makes that error go away, and allows the library to build. Are there any other dependencies on a newer CMake version than declared, or should this change be applied to allow people with older CMake versions to build?

**Comment by GlitchedPolygons** [comment]
Ah, good catch! No I'll just increase the min cmake v.
Thanks :)
