### ISSUE TITLE
l8w8jwt_decode documentation issue

### ISSUE THREAD

**Issue by firthmj** [GlitchedPolygons/l8w8jwt#14]
The documentation for this function says of the "out_claims" parameter both to "REMEMBER to call l8w8jwt_free() on it once you're done using it" and to "REMEMBER to call l8w8jwt_free_claims() on it once you're done using them". If both of these things are done, then you get a double free error - I'm assuming it is only the second that is correct?

**Comment by GlitchedPolygons** [comment]
That's correct, that specific one has a dedicated free function because it loops into them and frees them individually.

Thanks! I'll remove that first one.
