### ISSUE TITLE
[BUG] l8w8jwt_decode fails if there are structures in the JWT

### ISSUE THREAD

**Issue by firthmj** [GlitchedPolygons/l8w8jwt#16]
**Describe the bug**
If there are more complex data structures in the JWT than just single level values, then l8w8jwt_decode fails with a L8W8JWT_DECODE_FAILED_INVALID_TOKEN_FORMAT error.

I saw this when there was an embedded array (as "aud" is recommended to be an array), but think it may happen for nested objects too

**To Reproduce**
I was working with the RS512 example, so to make it happen here:
Add a structure to the payload_claims array in encode.c similar to the following:

        {
            .key = "aud2",
            .key_length = strlen("aud2"),
            .value = "[ \"*.jwt.example.com\" ]",
            .value_length = strlen("[ \"*.jwt.example.com\" ]"),
            .type = L8W8JWT_CLAIM_TYPE_ARRAY
        },

The encode app will compile and run, but if the JWT output is passed to the partner decode app it will fail with a line saying:
"l8w8jwt_decode_rs512 function returned  (code 600)."

**Expected behavior**
The JWT should be parsed by the decoder, and an "array" type claim be included in the output

**Additional context**
There is an additional small bug in the encode.c file, I will raise that as a separate issue

**Comment by GlitchedPolygons** [comment]
This is intentional to keep l8w8jwt lightweight and slim.

See issues #4 and #7 for a more in-detail log about this decision.

**Comment by firthmj** [comment]
For anyone else coming to this, it is possible to resolve this by making the following changes to the library "decode.c", to get it to skip across the token elements return by jsmn that aren't direct children of the root:

```
--- a/src/decode.c
+++ b/src/decode.c
@@ -19,6 +19,7 @@ extern "C" {
 #endif
 
 #define JSMN_STATIC
+#define JSMN_PARENT_LINKS
 
 #include "l8w8jwt/util.h"
 #include "l8w8jwt/decode.h"
@@ -137,9 +138,15 @@ static int l8w8jwt_parse_claims(chillbuff* buffer, char* json, const size_t json
                 break;
             case JSMN_OBJECT:
                 claim.type = L8W8JWT_CLAIM_TYPE_OBJECT;
+                // Skip children...
+                while (tokens[i+1].parent != 0 && i < r)
+                  i++;
                 break;
             case JSMN_ARRAY:
                 claim.type = L8W8JWT_CLAIM_TYPE_ARRAY;
+                // Skip children...
+                while (tokens[i+1].parent != 0 && i < r)
+                  i++;
                 break;
             case JSMN_STRING:
                 claim.type = L8W8JWT_CLAIM_TYPE_STRING;
```

The full item still seems to be returned correctly, at least for an array.

It does require enabling the "parent links" function in JSMN, so it may still break the "lightweight" target.

**Comment by GlitchedPolygons** [comment]
> 
> 
> For anyone else coming to this, it is possible to resolve this by making the following changes to the library "decode.c", to get it to skip across the token elements return by jsmn that aren't direct children of the root:
> 
> ```
> --- a/src/decode.c
> +++ b/src/decode.c
> @@ -19,6 +19,7 @@ extern "C" {
>  #endif
>  
>  #define JSMN_STATIC
> +#define JSMN_PARENT_LINKS
>  
>  #include "l8w8jwt/util.h"
>  #include "l8w8jwt/decode.h"
> @@ -137,9 +138,15 @@ static int l8w8jwt_parse_claims(chillbuff* buffer, char* json, const size_t json
>                  break;
>              case JSMN_OBJECT:
>                  claim.type = L8W8JWT_CLAIM_TYPE_OBJECT;
> +                // Skip children...
> +                while (tokens[i+1].parent != 0 && i < r)
> +                  i++;
>                  break;
>              case JSMN_ARRAY:
>                  claim.type = L8W8JWT_CLAIM_TYPE_ARRAY;
> +                // Skip children...
> +                while (tokens[i+1].parent != 0 && i < r)
> +                  i++;
>                  break;
>              case JSMN_STRING:
>                  claim.type = L8W8JWT_CLAIM_TYPE_STRING;
> ```
> 
> The full item still seems to be returned correctly, at least for an array.
> 
> It does require enabling the "parent links" function in JSMN, so it may still break the "lightweight" target.

Thank you so much for your contribution! :)

**Comment by GlitchedPolygons** [comment]
Hi there, sorry for the extreme delay. I didn't have time to look into this at all unfortunately :/

I will eventually though!

**Comment by DareDeska** [comment]
> For anyone else coming to this, it is possible to resolve this by making the following changes to the library "decode.c", to get it to skip across the token elements return by jsmn that aren't direct children of the root:
> 
> ```
> --- a/src/decode.c
> +++ b/src/decode.c
> @@ -19,6 +19,7 @@ extern "C" {
>  #endif
>  
>  #define JSMN_STATIC
> +#define JSMN_PARENT_LINKS
>  
>  #include "l8w8jwt/util.h"
>  #include "l8w8jwt/decode.h"
> @@ -137,9 +138,15 @@ static int l8w8jwt_parse_claims(chillbuff* buffer, char* json, const size_t json
>                  break;
>              case JSMN_OBJECT:
>                  claim.type = L8W8JWT_CLAIM_TYPE_OBJECT;
> +                // Skip children...
> +                while (tokens[i+1].parent != 0 && i < r)
> +                  i++;
>                  break;
>              case JSMN_ARRAY:
>                  claim.type = L8W8JWT_CLAIM_TYPE_ARRAY;
> +                // Skip children...
> +                while (tokens[i+1].parent != 0 && i < r)
> +                  i++;
>                  break;
>              case JSMN_STRING:
>                  claim.type = L8W8JWT_CLAIM_TYPE_STRING;
> ```
> 
> The full item still seems to be returned correctly, at least for an array.
> 
> It does require enabling the "parent links" function in JSMN, so it may still break the "lightweight" target.

I tested the following, similar to you change but no nedd of ksmn's parent

                //skip children...
                while (tokens[i+1].end <= value.end && i < r) i++;

**Comment by GlitchedPolygons** [comment]
@bassena @DareDeska @firthmj Hi everyone, hope you're all well and started nicely into 2024 :)

Sorry for the insane delay.

I have updated l8w8jwt's dependencies and addressed some of the issues/feature requests that users have reported, including this one. While it still is not recommended to have non-flat claim values, there is now an "official" workaround that at least allows users to decode and validate JWTs while receiving the decoded payload JSON string out from the `l8w8jwt_decode_raw` function, so that the critical claims can be parsed externally. Check out #15 for more details on how this was suggested.

Thanks again for the issue submission.

Check out release 2.3.0 here: 

https://github.com/GlitchedPolygons/l8w8jwt/releases/tag/2.3.0

:)

Cheers, and have a wonderful 2024!
