### ISSUE TITLE
[BUG] rs512 example encode.c is missing set of nbf parameter

### ISSUE THREAD

**Issue by firthmj** [GlitchedPolygons/l8w8jwt#17]
**Describe the bug**
The "encode.c" file in the "examples/rs512" folder does not have a line to set "params.nbf". The partner "decode.c" does set "params.validate_nbf", which means it is looking for this field to be present and set to a valid value.

**To Reproduce**
Compile and run the supplied encode.c in the examples/rs512 folder.
Feed the generated JWT to the decode.c example (by replacing the text of the JWT static variable).
Compile and run the decode.c example.
It will likely indicate that the JWT validation failed with error 32, which is "L8W8JWT_NBF_FAILURE"

**Expected behavior**
The encode.c example should set a value for NBF, and then the decode.c example would indicate 0 for "everything parsed OK"

**Comment by GlitchedPolygons** [comment]
Not a bug, this is just an example. Failed validations are also valuable for understanding the flow.

**Comment by GlitchedPolygons** [comment]
Anything inside `examples/`  is volatile and merely serves to provide demo usage of the library functions: it's in no way representative of a final integration!

What I find particularly interesting is how failures are handled: that's more of a documentation related issue I think tho :)

E.g. it should be made clearer when decoding a token failed VS. verifying its signature: the return code is for deserialization/decoding status, the output validation argument is for actual token validity.
