### ISSUE TITLE
How to install？

### ISSUE THREAD

**Issue by mpv945** [GlitchedPolygons/l8w8jwt#18]
I now use Debian system.

step 1: git clone --recursive https://github.com/GlitchedPolygons/l8w8jwt.git

step 2: cd l8w8jwt && bash build.sh

step 3: cd build/   

l8w8jwt-2.0.0-linux-x86_64.tar.gz ? How to follow up

**Comment by GlitchedPolygons** [comment]
You could also open the `bash-sh` file and copy the first CMake command and execute it in your own `some-other-dir` sub-folder, and then run `make && sudo make install` but that installs it system wide and without any guarantee.

It's probably better to just include the l8w8jwt source into your project and use CMake's `add_subdirectory` to directly include l8w8jwt in your build. Check the README.md for that :)

**Comment by mpv945** [comment]
vultr:~/nginx-src/l8w8jwt$ gcc l8w8jwt1.c -o l8w8jwt1
/usr/bin/ld: /tmp/ccaWW1YT.o: in function `main':
l8w8jwt1.c:(.text+0x16): undefined reference to `l8w8jwt_encoding_params_init'
/usr/bin/ld: l8w8jwt1.c:(.text+0xa9): undefined reference to `l8w8jwt_encode'
/usr/bin/ld: l8w8jwt1.c:(.text+0xdf): undefined reference to `l8w8jwt_free'
collect2: error: ld returned 1 exit status

**Comment by mpv945** [comment]
> 您也可以打开文件并复制第一个 CMake 命令，并在您自己的子文件夹中执行它，然后运行，但安装系统很宽，没有任何保证。`bash-sh``some-other-dir``make && sudo make install`
> 
> 最好将 l8w8jwt 源包含到您的项目中，并使用 CMake 的源直接将 l8w8jwt 纳入您的构建中。检查 README.md 是否有该:)`add_subdirectory`



可否提供二进制的包，以命令运行？

Can binary packages be provided to run with commands?
