### ISSUE TITLE
Backslashes in claims are not escaped in the JSON string

### ISSUE THREAD

**Issue by valentino-fiorin** [GlitchedPolygons/l8w8jwt#25]
When the value of claim contains a backslash, the l8w8jwt does not escape it to produce a valid JSON.

**Comment by GlitchedPolygons** [comment]
@valentino-fiorin 

Hi there,

Thanks for reporting this! :)

I'll look into it as soon as possible.

Meanwhile, check out the new GUI I wrote for this library:

https://github.com/GlitchedPolygons/l8w8jwtgui

I'm still working on the README.md + documentation, but should be ready in the coming days.

**Comment by GlitchedPolygons** [comment]
@valentino-fiorin  Done, I pushed the fix to master and created a new patch release: [v2.1.5](https://github.com/GlitchedPolygons/l8w8jwt/releases/tag/2.1.5)

Thanks for pointing this out! :)

**Comment by valentino-fiorin** [comment]
Great! I'll upgrade to the new tag out and give it a try. 
Thanks for the quick turnaround!
