### ISSUE TITLE
complie warning in c++ project

### ISSUE THREAD

**Issue by robin2014** [GlitchedPolygons/l8w8jwt#27]
I use the static library in my c++ project,but it always warning when complie:
warning: conversion from string literal to 'char *' is deprecated [-Wc++11-compat-deprecated-writable-strings]
.value = "JEi2K66Z7Y",
what can i do to avoid this warning?

**Comment by GlitchedPolygons** [comment]
> I use the static library in my c++ project,but it always warning when complie: warning: conversion from string literal to 'char *' is deprecated [-Wc++11-compat-deprecated-writable-strings] .value = "JEi2K66Z7Y", what can i do to avoid this warning?

You can either ignore the warning (it should still work, even if assigning string literals to `char*` in C++ is _Not Nice_), ooor you can also do a `const_cast<char*>("JEi2K66Z7Y")` instead of directly assigning the string literal :)

Let me know if this helps. I'll close this for the time being 👍
