### ISSUE TITLE
[BUG] Escaped forward slash (/) not handled correctly in claims

### ISSUE THREAD

**Issue by rhythmize** [GlitchedPolygons/l8w8jwt#30]
**Describe the bug**
I see that the support for unescaping backslashes was added in this [commit](https://github.com/GlitchedPolygons/l8w8jwt/commit/8949986b8f14ed529fa8f10af18f8dad1c617897), and in the current state if a quote (") is encountered, that is preserved [here](https://github.com/GlitchedPolygons/l8w8jwt/blob/master/src/decode.c#L126). I'm facing the same problem with the forward slashes where I have a token where the issuer seems to have escaped forward slash (/) which is not correctly parsed while decoding the token using this library, leading to **Invalid Issuer** error. 
I tried decoding the token on jwt.io and other libraries and these escaped forward slashes are correctly handled, that's why reporting the bug here.

**To Reproduce**
1. Add this test in `tests/tests.c`
```
static void test_my_jwt_token_decode()
{
    int r;
    char jwt[] = "eyJhbGciOiJSUzI1NiIsImtpZCI6IkE3NHBUeDlIMDdMd1kyaGFrZVdPS0ZOZTNtaDhaNjZ3ZlFnQUhyME5OLUEiLCJ0eXAiOiJKV1QifQ.eyJleHAiOjE2NzAxNjM4MjQsImZsaWdodF9vcGVyYXRpb25faWQiOiIzNDA4YmNlOS1kYmFiLTQ2NjUtYWJmYy04ZWEwM2IwYWQ4NzEiLCJmbGlnaHRfcGxhbl9pZCI6IjEyODE4ZTg3LTRjOTYtNGU0Yy04YzYzLTgyYjhlMTJjM2I3MyIsImlhdCI6MTY3MDE2MDIyNCwiaXNzIjoiaHR0cHM6XC9cL3Rlc3RcL2RvbWFpblwvIiwicGxhbl9maWxlX2hhc2giOiJhMmEyMDFlZmExMTFkZGU1YWFhOGY0MmI3YjQ2ZDE3YjU5NWUzOWQ4NTA1MDBkYmFjZDlmNzlhZWYwYmJmNjhlIiwic2NvcGUiOiIiLCJzdWIiOiJnMzdsWGlmQVFvQmZWdVFaeFQzVkpGalhJTWdkZlhJT3BhMkxkV0JRQGNsaWVudHMiLCJ0eXAiOiJCZWFyZXIifQ.erPylOUbAxVz03P6f5dCyjWgRA1RDUW-5pC49OGTfDEEmM9HElXx2lH5_7-C-l0HoUjypaix_s2PC9jYUUIGBsdL_2Mfary2-cxOMDyGrbfP39rD-Fq7CWrvSlqz8k9dPEEhW06Jjq2ujvcY6277Po7pXrC7PyhL3En7B3b3sUC6gk-FXVAI9XzTpxnSN5w3g7vxEi1JgI8EyfeWT1usAST8UdKYrJEzmJOvIaloq1zz1oJb9jXFGj3hCABU4Ky58ibvaiveucf5Fq8essC2jIKUBfnAy43gsj6h6kPTy5PEugSLXoomNAXthnUFckmJjY0hNwQc5yLLRa--f9ObsgFO0dKquqwGlU0BbuBZU0Dyh5-IUqNfMEG76nnr5TlzjgMusVDjCSEdDBB2ef6xdBcMiWMA-8Po2Qyd9wsKhg4ud_Hxzmutp-sEb1fhH7QcSfdeNRWnhmuGgNPaYQtx46TN8sm0IWfcVa9EUTC7IdUBAOX-o0Ob8uHjFzq97YjHawZyosj5ajgHzc8gQDIyykXO1a45r0hdMOXw7eGQ_oOC_ZWHolvNmYg38mkbpErXTUHt_Wzl3B3xuMAwMPeBskI4l_zrvmgEcGzuM1B1Igqk3pbLqJIbRBHx-VcenwevId-kGIHzfKVYmtPRO9Y6k4_njvYFYc6TcvpscmPmfGM";
    size_t jwt_length = strlen(jwt);

    struct l8w8jwt_decoding_params decoding_params;
    l8w8jwt_decoding_params_init(&decoding_params);

    decoding_params.alg = L8W8JWT_ALG_RS256;
    decoding_params.jwt = jwt;
    decoding_params.jwt_length = jwt_length;
    decoding_params.verification_key = (unsigned char*)RSA_PUBLIC_KEY;
    decoding_params.verification_key_length = strlen(RSA_PUBLIC_KEY);
    
    struct l8w8jwt_claim claims;
    struct l8w8jwt_claim* ref = &claims;
    size_t claims_count;

    enum l8w8jwt_validation_result validation_result;
    r = l8w8jwt_decode(&decoding_params, &validation_result, &ref, &claims_count);

    struct l8w8jwt_claim* issClaim = l8w8jwt_get_claim(ref, claims_count, "iss", 3);
    printf(">>> claim: %s : %s\n", issClaim->key, issClaim->value);
}
```
2. Add the test in TEST_LIST
`{ "test_my_jwt_token_decode",  test_my_jwt_token_decode },`
3. Run ./test.sh
4. Test result
![image](https://user-images.githubusercontent.com/11855299/205493019-1bd54a1e-4338-4e89-8676-8c7dc91080a4.png)

**Expected behavior**
Expected claim should be: `https://test/domain/`
![image](https://user-images.githubusercontent.com/11855299/205469070-c74118a3-6923-4b94-b707-9972fc991864.png)

**Desktop (please complete the following information):**
 - OS: Linux

**Additional context**
I'm trying to use this library for validating jwt token which are generated and signed remotely and probably even by some other implementation of jwt.

**Comment by GlitchedPolygons** [comment]
@rhythmize Thanks for reporting this! I'll look into this asap. I already found a discrepancy by your CLI result and [the l8w8jwt GUI:](https://github.com/GlitchedPolygons/l8w8jwtgui)

<img width="522" alt="Screenshot 2022-12-04 at 11 35 37" src="https://user-images.githubusercontent.com/37942667/205485996-8d8c11d8-de1d-4583-8871-4b77a595041e.png">

I'll let you know as soon as I have progress :)

**Comment by rhythmize** [comment]
Hi @GlitchedPolygons, I further narrowed it down to a unittest for easier evaluation. Please see the updated description.

**Comment by GlitchedPolygons** [comment]
Thanks @rhythmize, you've been very helpful! Your extensive report helped me pinpoint and fix the issue very quickly :) kudos!

I just pushed commit `506a521` and the build pipelines are corrently testing and compiling. As soon as they're done I'll publish release `2.1.7` 😃 👍

**Comment by GlitchedPolygons** [comment]
@rhythmize  Done: https://github.com/GlitchedPolygons/l8w8jwt/releases/tag/2.1.7
