### ISSUE TITLE
[BUG] unnecessary extra newline check on key header delimiter

### ISSUE THREAD

**Issue by ygz999** [GlitchedPolygons/l8w8jwt#31]
**Describe the bug**
pem key discarded if header is not followed by a newline.

**To Reproduce**
Steps to reproduce the behavior (using a test app or L8W8JWTGUI):
1. provide a signature verification key, e.g. ES256
-----BEGIN PUBLIC KEY-----MFk...-----END PUBLIC KEY----
2. decode and verify a jwt will give error
"Failed to parse verification key!"

The cause is in <l8w8jwt>\lib\mbedtls\library\pem.c
int mbedtls_pem_read_buffer()
line 260:  else return( MBEDTLS_ERR_PEM_NO_HEADER_FOOTER_PRESENT );

This else-statement should be disabled.

**Expected behavior**
An extra "\n" is unnecessary after "-----BEGIN PUBLIC KEY-----"

**repo**
Most recent commit
506a52163ddb71829aa006a25962d7515d567e80 on master, tag: 2.1.7

**Desktop (please complete the following information):**
 - OS: Windows 10

**PS**
If one puts an extra \n, the error would be gone, e.g.
-----BEGIN PUBLIC KEY-----
MFk...-----END PUBLIC KEY----

**Comment by GlitchedPolygons** [comment]
Closed because won't modify MbedTLS library because of this. If it has high prio please consider opening this issue directly on https://github.com/Mbed-TLS/mbedtls - but forking/modifying a dependency is never a good idea :)

Thanks nonetheless for helping documenting this detail!
