### ISSUE TITLE
failed to decode array/object 

### ISSUE THREAD

**Issue by ygz999** [GlitchedPolygons/l8w8jwt#32]
**Describe the bug**
Can't decode array of objects

**To Reproduce**
1. set payload to something as follows
 "name": "John Doe",
  "admin": true,
  "iat": 1516239022,
  "iss": "https://us2.namequery.com/jwks.json",
  "aud": "hereIam",
  "keys":[
      {
         "kty":"OKP",
         "use":"sig",
         "crv":"Ed448",
         "kid":"bOx3fHXSLaWVHzilUZbpNRY0Ot-g5NdRMfdVAHKIVzE",
         "x":"iyENW7C_l93h8Ev43MZ-EU5Ix8RmpHA89-6rBCgVLc1S0ORdcMJjwtftv-yDU--ygDxXR-5MoycA",
         "alg":"EdDSA"
      },
      {
         "kty":"OKP",         "d":"k4lDLCdZsEgfT6WMWHEqzW34mHZ9pezpKk2XUti89VxhevWRR3OrsdyzUShVVEQIvw-_yU66gyg",
         "use":"sig",
         "crv":"X448",         "kid":"7MXgy5yq6WkBQqe4oT3XG6INftCR0HuQlDWy4ttiNo4",
         "x":"Mu0DQEjOf8os_F3LvGqRnLvtuV-MHq7aqIZ4QdvaJpUfJNtWu7GH4MYYbeihHgtGOD8bwp4_vZM",
         "alg":"EdDSA"
      }]
}
2. Calling l8w8jwt_decode failed with L8W8JWT_DECODE_FAILED_INVALID_TOKEN_FORMAT, likely due to l8w8jwt_parse_claims not handling JSMN_ARRAY/JSMN_OBJECT

**Comment by GlitchedPolygons** [comment]
This is intentional to keep l8w8jwt lightweight and slim.

See issues https://github.com/GlitchedPolygons/l8w8jwt/issues/4 and https://github.com/GlitchedPolygons/l8w8jwt/issues/7 for a more in-detail log about this decision.
