### ISSUE TITLE
l8w8jwt_decode_raw added in PR #41 still cannot handle arrays

### ISSUE THREAD

**Issue by ufownl** [GlitchedPolygons/l8w8jwt#42]
Hi, the function `l8w8jwt_decode_raw` added in PR #41 still cannot handle arrays. I found that the key to the array parsing issue lies in the function `l8w8jwt_parse_claims`, which is called by `l8w8jwt_decode_raw`. So it still returns `L8W8JWT_DECODE_FAILED_INVALID_TOKEN_FORMAT` when there are array claims.

**Comment by GlitchedPolygons** [comment]
> Hi, the function `l8w8jwt_decode_raw` added in PR #41 still cannot handle arrays. I found that the key to the array parsing issue lies in the function `l8w8jwt_parse_claims`, which is called by `l8w8jwt_decode_raw`. So it still returns `L8W8JWT_DECODE_FAILED_INVALID_TOKEN_FORMAT` when there are array claims.

@ufownl Oh shit, I must be **very** tired not to have tested that... Yep, I'll look into this soon. Thanks :S

**Comment by ufownl** [comment]
I'm not familiar with jsmn, if it could just skip the children tokens, and keep the raw JSON string in the array/object claims, that will be fine, in my opinion.

**Comment by GlitchedPolygons** [comment]
Producing and signing release and binaries asap...

**Comment by GlitchedPolygons** [comment]
Done. https://github.com/GlitchedPolygons/l8w8jwt/releases/tag/2.3.1
