### ISSUE TITLE
External JSON parsing error when object/array claim contains escape characters

### ISSUE THREAD

**Issue by ufownl** [GlitchedPolygons/l8w8jwt#43]
Hi, version 2.3.1 still has a small problem. If an object/array claim contains escape characters, it will lead external JSON parsing error. I checked the relevant code and found that the issue is [here](https://github.com/GlitchedPolygons/l8w8jwt/blob/729e438a3b9085ef4437b0aecd0af83c9b0d0a9b/src/decode.c#L338). The object/array claims should not be unescaped, they should retain their original content for the external JSON parser.

Additionally, I found that the function `l8w8jwt_unescape_claim` only escapes `\"` for keys, `\"` and `\/` for values, and no other escape characters. I'm not sure if this is a feature or an issue.

**Comment by GlitchedPolygons** [comment]
@ufownl Hi :)

Unfortunately I don't have a lot of time to look into this atm, would it be ok for you to post more info (such as token used for decoding, expected behavior and actual behavior)? 
I'm also open to review pull requests in case you feel like fixing it yourself 😃

**Comment by ufownl** [comment]
This issue has been fixed in PR #44, so it can be closed.
