### ISSUE TITLE
l8w8jwt_decode_raw_no_validation requires a verification key

### ISSUE THREAD

**Issue by Forbinn** [GlitchedPolygons/l8w8jwt#47]
The `l8w8jwt_decode_raw_no_validation` require the `l8w8jwt_decoding_params.verification_key` to be non-NULL and the `l8w8jwt_decoding_params.verification_key_length` to be > 0 even though this function doesn't actually use them and shouldn't use them as the name of the function indirectly implies.

This is due to the fact that `l8w8jwt_decode_raw_no_validation` calls `l8w8jwt_validate_decoding_params` which in turns do those validation checks.

This is not a big deal as you just have to set a dummy (but valid) value to both of those fields and you are good to go but I just wanted to mentioned it here in case this wasn't an intended behavior.

**Comment by GlitchedPolygons** [comment]
@Forbinn Thanks for pointing this out! :)

Any suggestions on what would be a more elegant parametrization and/or way of handling that function's arguments?

**Comment by Forbinn** [comment]
I see 2 possibles solutions:

1. Change the prototype of the `l8w8jwt_validate_decoding_params` function that will add a new parameter telling it what should be checked (a OR combination of flags. e.g. `l8w8jwt_validate_decoding_params(&params, L8W8JWT_DECODE_PARAM_CHECK_JWT | L8W8JWT_DECODE_PARAM_CHECK_VERIFICATION_KEY)`). Note that if you choose to do this then the `l8w8jwt_validate_encoding_params` function will probably have to be changed as well in order to keep the API consistent.
2. Remove the verification key check from the `l8w8jwt_validate_decoding_params` function and do it only where it is used which in this case is in `l8w8jwt_verify_signature` around line 494.

Since `l8w8jwt_validate_decoding_params` is part of the public API, it should be noted that any solution would break the API and is also why I'm not sure this should be fixed at all since there is an easy workaround. But that is not for me to decide.

Of course, this is merely a suggestion and you may choose to do something completely different or even nothing at all.

**Comment by GlitchedPolygons** [comment]
@Forbinn Thanks! I'll think about it, and look into an update as soon as I have time :)

Again, thanks for your contribution. Highly appreciated 🙏

**Comment by GlitchedPolygons** [comment]
Fixed in [release 2.4.0](https://github.com/GlitchedPolygons/l8w8jwt/releases/tag/2.4.0) 🙂
