### ISSUE TITLE
Generating dll for use in LoadRunner for performance testing 32bit and 64 bit

### ISSUE THREAD

**Issue by rsarpal** [GlitchedPolygons/l8w8jwt#5]
hi,

I am trying to use this library with Performance testing tool called LoadRunner.  I have generated the dll using the "bash build.sh" which has been provided in the Repo, but that dll fails with "Error: C interpreter run time error:  Error -- File error : LoadLibrary(l8w8jwt.dll) failed" in loadrunner.

Are there some instructions available to generate 32 bit dll? I could try to use that as well.

Br,

**Comment by GlitchedPolygons** [comment]
That error arises inside build.sh?

Or when you tried to use it?

**Comment by rsarpal** [comment]
Error is thrown by the Loadrunner tool  when i try to use it.

**Comment by GlitchedPolygons** [comment]
You're on Windows. Did you link whatever code you're compiling against the symbols l8w8jwt.lib? Windows requires that before loading l8w8jwt.dll from the path.

**Comment by GlitchedPolygons** [comment]
Also: `build.sh` builds x64 in Release mode by default on Windows. If you need anything else, nothing stops you from customizing the build using CMake yourself :)

I'm sorry but I don't have any experience with LoadRunner, and it's also out of the scope of this library, so I'm closing this issue for now.

**Comment by rsarpal** [comment]
Hi,

I got the dll to work , however Loadrunner(LR) found the methods but not the structs declarations in the header files. So i had to add  all the header files seperately in LR .

Now I am trying to test it with the Example code "Encoding and signing a token" which is given in the Documentation here. The printf is returning r=100  L8W9JWT_NULL_ARG

What could be the reason for this?

Br
